name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
      continue-on-error: true
      
    - name: Create requirements file if it doesn't exist
      run: |
        if not exist requirements.txt (
          echo tkinter >> requirements.txt
        )
      shell: cmd
      
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --icon=windows_update_toggle.ico windows_update_toggle.py
        
    - name: Create Release and Upload Asset
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: ./dist/windows_update_toggle.exe
        allow_override: true
        
    - name: Upload Artifact (for non-tag builds)
      uses: actions/upload-artifact@v4
      with:
        name: windows-update-toggle
        path: ./dist/windows_update_toggle.exe