name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
      continue-on-error: true
      
    - name: Create requirements file if it doesn't exist
      run: |
        if not exist requirements.txt (
          echo tkinter >> requirements.txt
        )
      shell: cmd
      
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --icon=windows_update_toggle.ico windows_update_toggle.py
        
    - name: Create and Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: softprops/action-gh-release@v2.2.2
      with:
        files: ./dist/windows_update_toggle.exe
        name: Release ${{ github.ref_name }}
        generate_release_notes: true